### ISSUE TITLE
error about body_rot reshaping in training diffusion smpl

### ISSUE THREAD

**Issue by chrenx** [Sirui-Xu/InterDiff#8]
I got the following error:

body_rot = rotvec_to_rotmat(body_pred[:, :, :, :-3]).view(self.args.diverse_samples, T, B, nJ * 9)
RuntimeError: shape '[10, 35, 32, 603]' is invalid for input of size 5241600

Error came from the calc_loss function in train_diffusion_smpl.py where the code was trying to reshape the body_rot. I am lost why we need to multiply nJ by 9 in reshaping and why nJ needs to be // 3.

**Comment by Sirui-Xu** [comment]
Hi,

For the first nJ = nJ // 3, where nJ on the right-hand side represents the total number of joints multiplied by 3 (because of the axis-angle representation), we divide by 3 to obtain the actual number of joints. This is because each joint rotation is described by 3 values in the axis-angle representation.

When we multiply nJ by 9, we convert the axis-angle representation to a rotation matrix representation. A rotation matrix is a 3x3 matrix, hence 9 values in total for each joint. nJ * 9 gives us the number of elements required to represent the rotation of all joints.

Best

**Comment by chrenx** [comment]
Thanks for your reply Sirui!
I double check the axis-angle representation, and it seems to use (unit vector, angle theta). I wonder what these 3 values are. I didn't find this description in the paper. Maybe I missed it. 

BTW, i was trying to reproduce the work by following interdiff/README.md, but there was an reshaping error as following:
      body_rot = rotvec_to_rotmat(body_pred[:, :, :, :-3]).view(self.args.diverse_samples, T, B, nJ * 9)
      RuntimeError: shape '[10, 35, 32, 603]' is invalid for input of size 5241600
I didn't change any part of the code. I wonder if you've ever encounter this problem.

**Comment by Sirui-Xu** [comment]
Hello, 

Sorry about that. Just remove L425 where I concatenate rotation with others before doing the conversion, which caused a duplicate in the GT, resulting in a misalignment. 

Best
